name: Deploy-To-Firebase

on: 
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.17
      uses: actions/setup-node@v1
      with:
        node-version: 16.17
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build --prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: "${{ secrets.GOOGLE_PROJECT_ID }}"
